name: Security Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

permissions:
  contents: read

jobs:
  security_checks:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo tools
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit-tools
      
      - name: Install cargo-audit
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit
          fi
      
      - name: Run cargo-audit
        run: |
          cargo audit --json > audit-results.json || echo "::warning::Security vulnerabilities found. Check the artifact for details."
      
      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-results
          path: audit-results.json
          retention-days: 7
          
      - name: Check for security script
        run: |
          if [ -f "security-check.sh" ]; then
            chmod +x security-check.sh
            ./security-check.sh || echo "::warning::Security script reported issues"
          else
            echo "Security check script not found. Skipping custom checks."
          fi