max_width = 100
tab_spaces = 4
edition = "2021"
use_small_heuristics = "Max"
use_field_init_shorthand = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
wrap_comments = true
comment_width = 100
chain_width = 80
fn_call_width = 80
attr_fn_like_width = 80
empty_item_single_line = true
where_single_line = true
overflow_delimited_expr = true
version = "Two"
normalize_comments = true
normalize_doc_attributes = true
format_generated_files = false
condense_wildcard_suffixes = true